//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: payload.fbe
// FBE version: 1.14.1.0
//------------------------------------------------------------------------------

package proto

import "errors"
import "github/lwileczek/goBenchmarkSerialization/types/fbe"

// Workaround for Go unused imports issue
var _ = errors.New
var _ = fbe.Version

// Fast Binary Encoding PbPayload model
type PbPayloadModel struct {
    // Model buffer
    buffer *fbe.Buffer

    // Field model
    model *FieldModelPbPayload
}

// Create a new PbPayload model
func NewPbPayloadModel(buffer *fbe.Buffer) *PbPayloadModel {
    return &PbPayloadModel{buffer: buffer, model: NewFieldModelPbPayload(buffer, 4)}
}

// Get the model buffer
func (m *PbPayloadModel) Buffer() *fbe.Buffer { return m.buffer }
// Get the field model
func (m *PbPayloadModel) Model() *FieldModelPbPayload { return m.model }

// Get the model size
func (m *PbPayloadModel) FBESize() int { return m.model.FBESize() + m.model.FBEExtra() }
// // Get the model type
func (m *PbPayloadModel) FBEType() int { return m.model.FBEType() }

// Check if the struct value is valid
func (m *PbPayloadModel) Verify() bool {
    if (m.buffer.Offset() + m.model.FBEOffset() - 4) > m.buffer.Size() {
        return false
    }

    fbeFullSize := int(fbe.ReadUInt32(m.buffer.Data(), m.buffer.Offset() + m.model.FBEOffset() - 4))
    if fbeFullSize < m.model.FBESize() {
        return false
    }

    return m.model.Verify()
}

// Create a new model (begin phase)
func (m *PbPayloadModel) CreateBegin() int {
    fbeBegin := m.buffer.Allocate(4 + m.model.FBESize())
    return fbeBegin
}

// Create a new model (end phase)
func (m *PbPayloadModel) CreateEnd(fbeBegin int) int {
    fbeEnd := m.buffer.Size()
    fbeFullSize := fbeEnd - fbeBegin
    fbe.WriteUInt32(m.buffer.Data(), m.buffer.Offset() + m.model.FBEOffset() - 4, uint32(fbeFullSize))
    return fbeFullSize
}

// Serialize the struct value
func (m *PbPayloadModel) Serialize(value *PbPayload) (int, error) {
    fbeBegin := m.CreateBegin()
    err := m.model.Set(value)
    fbeFullSize := m.CreateEnd(fbeBegin)
    return fbeFullSize, err
}

// Deserialize the struct value
func (m *PbPayloadModel) Deserialize() (*PbPayload, int, error) {
    value := NewPbPayload()
    fbeFullSize, err := m.DeserializeValue(value)
    return value, fbeFullSize, err
}

// Deserialize the struct value by the given pointer
func (m *PbPayloadModel) DeserializeValue(value *PbPayload) (int, error) {
    if (m.buffer.Offset() + m.model.FBEOffset() - 4) > m.buffer.Size() {
        value = NewPbPayload()
        return 0, nil
    }

    fbeFullSize := int(fbe.ReadUInt32(m.buffer.Data(), m.buffer.Offset() + m.model.FBEOffset() - 4))
    if fbeFullSize < m.model.FBESize() {
        value = NewPbPayload()
        return 0, errors.New("model is broken")
    }

    err := m.model.GetValue(value)
    return fbeFullSize, err
}

// Move to the next struct value
func (m *PbPayloadModel) Next(prev int) {
    m.model.FBEShift(prev)
}
